import{useMemo,useState}from'react';import{Routes,Route,Link,useLocation,useNavigate,useParams,Navigate}from'react-router-dom';import{AnimatePresence,motion}from'framer-motion';import{Search,Heart,ShoppingBag,User,Menu,ArrowRight,Star,Repeat2,Sparkles,BookOpen,ChevronRight,SlidersHorizontal,Grid2X2,List,MapPin,UploadCloud,MessageCircle,Wallet,Package,Settings,Home,Compass,Sun,Moon,X,Check,Plus,Minus,Bell,Send,Camera,Mic,ScanLine,Activity}from'lucide-react';import{books,categories}from'./data';import{NewHome,NewHeader}from'./Home';import { ExchangeDashboard } from './ExchangeDashboard';import { ProfilePage, OrdersPage, WalletPage, NotificationsPage, ChatPage, SettingsPage } from './AccountPages';import { CommunityPage } from './CommunityPage';import { CategoriesPage } from './CategoriesPage';

type Book=typeof books[number];
const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
function Cover({b,large=false}:{b:Book,large?:boolean}){return <div className={'cover '+(large?'large':'')} style={{background:b.color}}><div className="coverOrb" style={{background:b.accent}}/><small>BOOKLOOP EDITIONS</small><b>{b.title}</b><span>{b.author}</span></div>}
function Header({dark,setDark,cart,wish}:{dark:boolean,setDark:(v:boolean)=>void,cart:number,wish:number}){const[open,setOpen]=useState(false);return <><header><Link to="/" className="logo"><i><BookOpen size={18}/></i>bookloop</Link><nav><Link to="/explore">Discover</Link><Link to="/exchange">Exchange</Link><Link to="/sell">Sell a book</Link><Link to="/community">Community</Link></nav><div className="actions"><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><Link className="icon badge" to="/wishlist"><Heart/><em>{wish}</em></Link><Link className="icon badge" to="/cart"><ShoppingBag/><em>{cart}</em></Link><Link className="icon" to="/profile"><User/></Link><button className="icon mobile" onClick={()=>setOpen(!open)}><Menu/></button></div></header>{open&&<div className="mobileMenu"><Link to="/explore">Discover books</Link><Link to="/exchange">Exchange</Link><Link to="/sell">Sell a book</Link><Link to="/orders">Orders</Link></div>}</>}
function BookCard({b,onWish,onCart,wished}:{b:Book,onWish:(id:string)=>void,onCart:(id:string)=>void,wished:boolean}){return <motion.article className="bookCard" whileHover={{y:-7}}><div className="coverWrap"><Link to={'/book/'+b.id}><Cover b={b}/></Link><button aria-label="wishlist" className={'wish '+(wished?'active':'')} onClick={()=>onWish(b.id)}><Heart size={18} fill={wished?'currentColor':'none'}/></button><span className="condition">{b.condition}</span></div><Link to={'/book/'+b.id} className="bookTitle">{b.title}</Link><p>{b.author}</p><div className="bookMeta"><span><Star size={14} fill="currentColor"/> {b.rating}</span><span className="exchange"><Repeat2 size={14}/> Exchange</span></div><div className="price"><b>{money(b.price)}</b><s>{money(b.old)}</s><button onClick={()=>onCart(b.id)}><Plus size={17}/></button></div></motion.article>}
function SearchBox(){const nav=useNavigate();const[q,setQ]=useState('');return <form className="heroSearch" onSubmit={e=>{e.preventDefault();nav('/explore?q='+q)}}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by title, author, ISBN..."/><button type="button" title="Voice search"><Mic size={19}/></button><button type="button" title="Scan barcode"><ScanLine size={19}/></button><button className="searchBtn">Search</button></form>}
function HomePage({onWish,onCart,wish}:{onWish:(id:string)=>void,onCart:(id:string)=>void,wish:string[]}){return <main><section className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> A better chapter for every book</div><h1>Stories deserve<br/><em>another life.</em></h1><p>Buy, sell and exchange remarkable books with readers who care. Better for your shelf, your wallet, and the planet.</p><SearchBox/><div className="trust"><div className="avatars"><span>MS</span><span>AK</span><span>RN</span></div><b>50,000+ happy readers</b><span>•</span><span>4.9 average rating</span></div></div><div className="heroArt"><img src="/hero-books.png" alt="Curated hardcover books"/><div className="floatNote"><i><Check/></i><div><b>Quality checked</b><span>Every book, every time</span></div></div></div></section><section className="ticker"><span>12,000+ BOOKS</span><span>QUALITY CHECKED</span><span>EASY EXCHANGES</span><span>LOWER PRICES</span><span>PLANET FRIENDLY</span></section><section className="section"><div className="sectionHead"><div><small>CURATED FOR YOU</small><h2>Books worth getting lost in</h2></div><Link to="/explore">Explore all <ArrowRight/></Link></div><div className="bookGrid">{books.slice(0,5).map(b=><BookCard key={b.id} b={b} onWish={onWish} onCart={onCart} wished={wish.includes(b.id)}/>)}</div></section><section className="manifesto"><div><small>THE BOOKLOOP WAY</small><h2>Good books don't<br/>belong in boxes.</h2><p>Pass on the stories that moved you. Discover the ones that will. Every exchange keeps a book in motion—and a little more joy in the world.</p><Link className="primary" to="/exchange">Start an exchange <ArrowRight/></Link></div><div className="stats"><div><b>2.4m</b><span>pages given a second life</span></div><div><b>₹860</b><span>average reader savings</span></div><div><b>18k</b><span>books exchanged this month</span></div></div></section><section className="section"><div className="sectionHead"><div><small>FIND YOUR NEXT OBSESSION</small><h2>Browse by mood</h2></div></div><div className="categoryGrid">{categories.map((c,i)=><Link to={'/explore?category='+c} key={c}><span>0{i+1}</span><b>{c}</b><ChevronRight/></Link>)}</div></section><section className="cta"><div><small>YOUR SHELF HAS STORIES TO TELL</small><h2>Make room for<br/>what's next.</h2><p>List a book in under two minutes. You set the price; we make the rest beautifully simple.</p><Link className="lightBtn" to="/sell">Sell your first book <ArrowRight/></Link></div><div className="quote">“A reader lives a thousand lives before he dies.”<span>— George R. R. Martin</span></div></section></main>}
function Explore({onWish,onCart,wish}:{onWish:(id:string)=>void,onCart:(id:string)=>void,wish:string[]}){const[query,setQuery]=useState('');const[grid,setGrid]=useState(true);const filtered=books.filter(b=>(b.title+b.author+b.cat).toLowerCase().includes(query.toLowerCase()));return <main className="page"><div className="pageTitle"><small>THE CATALOGUE</small><h1>Find your next great read.</h1><p>Thoughtfully listed by readers across India.</p></div><div className="exploreSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search books, authors, categories..."/><button><SlidersHorizontal/> Filters</button></div><div className="catalog"><aside><b>Refine results</b>{['Category','Condition','Price range','Language','Availability'].map(x=><details key={x} open><summary>{x}<Plus/></summary><label><input type="checkbox"/> {x==='Category'?'Fiction & literature':x==='Condition'?'Like new':x==='Price range'?'Under ₹500':x==='Language'?'English':'Exchange available'}</label></details>)}</aside><section className="results"><div className="resultBar"><span><b>{filtered.length}</b> handpicked books</span><select><option>Most relevant</option><option>Price: low to high</option><option>Highest rated</option></select><button onClick={()=>setGrid(true)} className={grid?'active':''}><Grid2X2/></button><button onClick={()=>setGrid(false)} className={!grid?'active':''}><List/></button></div><div className={grid?'bookGrid four':'bookList'}>{filtered.map(b=><BookCard key={b.id} b={b} onWish={onWish} onCart={onCart} wished={wish.includes(b.id)}/>)}</div></section></div></main>}
function Detail({onWish,onCart,wish}:{onWish:(id:string)=>void,onCart:(id:string)=>void,wish:string[]}){const{id}=useParams();const b=books.find(x=>x.id===id)||books[0];return <main className="page"><div className="crumb"><Link to="/explore">Discover</Link> / {b.cat} / <b>{b.title}</b></div><section className="detail"><div className="gallery"><div className="thumbs"><Cover b={b}/><Cover b={{...b,color:'#E7E0D8'}}/></div><div className="mainCover"><Cover b={b} large/></div></div><div className="detailInfo"><span className="pill">{b.condition}</span><h1>{b.title}</h1><h3>by {b.author}</h3><div className="rating"><b><Star fill="currentColor"/> {b.rating}</b><span>128 reviews</span><span>•</span><span>342 wishlists</span></div><p className="description">A beautifully kept edition ready for its next reader. Inspected by BookLoop for cover, binding, pages and overall reading quality.</p><div className="priceLine"><b>{money(b.price)}</b><s>{money(b.old)}</s><span>{Math.round((1-b.price/b.old)*100)}% off</span></div><div className="delivery"><MapPin/><div><b>Delivering across India</b><span>Free delivery · Arrives in 3–5 days</span></div></div><div className="detailActions"><button className="buy" onClick={()=>onCart(b.id)}>Add to bag <ShoppingBag/></button><button onClick={()=>onWish(b.id)}><Heart fill={wish.includes(b.id)?'currentColor':'none'}/></button></div><Link to="/exchange" className="exchangeOffer"><Repeat2/><div><b>Prefer to exchange?</b><span>Trade one of your books and pay only the difference.</span></div><ArrowRight/></Link><div className="seller"><div className="sellerAvatar">AS</div><div><small>SOLD BY</small><b>Arjun's Reading Room</b><span><Star fill="currentColor"/> 4.9 · 216 sales</span></div><button><MessageCircle/> Chat</button></div></div></section><section className="section compact"><div className="sectionHead"><h2>You may also love</h2></div><div className="bookGrid">{books.filter(x=>x.id!==b.id).slice(0,5).map(x=><BookCard key={x.id} b={x} onWish={onWish} onCart={onCart} wished={wish.includes(x.id)}/>)}</div></section></main>}
function Sell(){const[step,setStep]=useState(1);const[done,setDone]=useState(false);if(done)return <main className="centerState"><i><Check/></i><h1>Your book is live!</h1><p>Readers can now find it in the BookLoop catalogue.</p><Link className="primary" to="/explore">View catalogue</Link></main>;return <main className="page narrow"><div className="pageTitle"><small>PASS IT FORWARD</small><h1>List a book.</h1><p>It takes less than two minutes.</p></div><div className="stepper">{['Book','Condition','Price','Review'].map((x,i)=><div className={step>=i+1?'active':''}><i>{step>i+1?<Check/>:i+1}</i><span>{x}</span></div>)}</div><div className="sellPanel"><div className="formArea">{step===1&&<><h2>What are you selling?</h2><label className="upload"><UploadCloud/><b>Drop book photos here</b><span>or click to browse · up to 6 images</span><input type="file" hidden/></label><div className="field"><label>Book title</label><input placeholder="e.g. The Midnight Library"/></div><div className="two"><div className="field"><label>Author</label><input placeholder="Author name"/></div><div className="field"><label>ISBN</label><input placeholder="978-..."/></div></div></>}{step===2&&<><h2>How's the condition?</h2><div className="conditionPick">{['New','Like new','Good','Fair'].map(x=><button>{x}<span>{x==='New'?'Unopened, perfect':x==='Like new'?'Barely read':x==='Good'?'Light wear':'Well loved'}</span></button>)}</div><div className="field"><label>Anything the buyer should know?</label><textarea placeholder="A small note about marks, highlights or wear..."/></div></>}{step===3&&<><h2>Set your price</h2><div className="priceInput"><span>₹</span><input defaultValue="399"/></div><div className="smartPrice"><Sparkles/><div><b>Smart price: ₹349–₹449</b><span>Based on similar books sold recently</span></div></div><label className="check"><input type="checkbox" defaultChecked/> Open to exchanges</label></>}{step===4&&<><h2>Ready for its next chapter?</h2><div className="reviewListing"><Cover b={books[4]}/><div><span>LIKE NEW</span><h3>The Midnight Library</h3><p>Matt Haig</p><b>₹399</b></div></div><p className="muted">By publishing, you confirm this listing is accurate and follows our community guidelines.</p></>}</div><div className="stepButtons"><button disabled={step===1} onClick={()=>setStep(step-1)}>Back</button><button className="primary" onClick={()=>step===4?setDone(true):setStep(step+1)}>{step===4?'Publish listing':'Continue'} <ArrowRight/></button></div></div></main>}
function SimplePage({type,items,onCart}:{type:string,items?:Book[],onCart?:(id:string)=>void}){return <main className="page"><div className="pageTitle"><small>YOUR BOOKLOOP</small><h1>{type}</h1><p>{type==='Wishlist'?'The books you’re saving for later.':type==='Cart'?'Your next reads, almost home.':'Everything in one calm, considered place.'}</p></div>{items&&items.length>0?<div className="bookGrid four">{items.map(b=><BookCard b={b} key={b.id} wished onWish={()=>{}} onCart={onCart||(()=>{})}/>)}</div>:<div className="emptyState"><p>No books here yet.</p></div>}</main>}
function ActivityPage() {
  const activities = [
    { id: 1, title: 'Your order has been quality checked', desc: 'The Midnight Library is on its way. Expect delivery by Thursday.', time: '2 hours ago', icon: Check, bg: '#dcebe2', color: '#285645' },
    { id: 2, title: 'Exchange request accepted', desc: 'Riya agreed to trade "Dune" for your copy of "Foundation".', time: 'Yesterday', icon: Repeat2, bg: '#eef4f0', color: '#287158' },
    { id: 3, title: '₹120 cashback added', desc: 'For your recent sale of "Atomic Habits".', time: '2 days ago', icon: Wallet, bg: '#f3e1d9', color: '#a84830' },
    { id: 4, title: 'New book matching your wishlist', desc: '"Project Hail Mary" was just listed in Like New condition.', time: '3 days ago', icon: Sparkles, bg: '#fff2cd', color: '#b2860b' },
    { id: 5, title: 'New message from Arjun', desc: '"Hey! Is the book still available for exchange?"', time: '4 days ago', icon: MessageCircle, bg: '#eef0ec', color: '#68706d' }
  ];
  return (
    <main className="page narrow">
      <div className="pageTitle" style={{ marginBottom: '40px' }}>
        <small>YOUR LOOP</small>
        <h1>Activity</h1>
        <p>Stay up to date with your book exchanges, orders, and community.</p>
      </div>
      <div className="activityPageGrid">
        <div className="activityList">
          {activities.map((a, i) => (
            <motion.div key={a.id} className="actCard" initial={{opacity:0, y: 15}} animate={{opacity:1, y: 0}} transition={{delay: i * 0.1}}>
              <div className="actIcon" style={{ background: a.bg, color: a.color }}>
                <a.icon size={22} />
              </div>
              <div style={{ flex: 1 }}>
                <h3>{a.title}</h3>
                <p>{a.desc}</p>
                <span>{a.time}</span>
              </div>
              <button><ChevronRight size={18} /></button>
            </motion.div>
          ))}
        </div>
        <aside className="actSidebar">
            <h3>Quick settings</h3>
            <div style={{ display: 'flex', flexDirection: 'column' }}>
                <label>
                    <input type="checkbox" defaultChecked />
                    Order updates
                </label>
                <label>
                    <input type="checkbox" defaultChecked />
                    Exchange requests
                </label>
                <label>
                    <input type="checkbox" defaultChecked />
                    Wishlist alerts
                </label>
                <label>
                    <input type="checkbox" />
                    Marketing emails
                </label>
            </div>
            <button>
                <Settings size={15} /> All notification settings
            </button>
        </aside>
      </div>
    </main>
  );
}
function Footer(){return <footer><div><Link to="/" className="logo"><i><BookOpen/></i>bookloop</Link><p>Beautiful books. Better circles.</p></div><div><b>Explore</b><Link to="/explore">Discover</Link><Link to="/exchange">Exchange</Link><Link to="/community">Community</Link></div><div><b>Account</b><Link to="/orders">Orders</Link><Link to="/wallet">Wallet</Link><Link to="/profile">Profile</Link></div><div><b>Company</b><a>About</a><a>Help centre</a><a>Contact</a></div><small>© 2026 BookLoop. Made for readers.</small></footer>}
export default function App(){const[dark,setDark]=useState(false);const[wish,setWish]=useState<string[]>(['deep']);const[cart,setCart]=useState<string[]>([]);const toggle=(id:string)=>setWish(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);const add=(id:string)=>setCart(c=>c.includes(id)?c:[...c,id]);const loc=useLocation();return <div className={dark?'app dark':'app'}><NewHeader dark={dark} setDark={setDark} cart={cart.length} wish={wish.length}/><AnimatePresence mode="wait"><motion.div key={loc.pathname} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.25}}><Routes><Route path="/" element={<NewHome onWish={toggle} onCart={add} wish={wish}/>}/><Route path="/explore" element={<Explore onWish={toggle} onCart={add} wish={wish}/>}/><Route path="/categories" element={<CategoriesPage />}/><Route path="/book/:id" element={<Detail onWish={toggle} onCart={add} wish={wish}/>}/><Route path="/sell" element={<Sell/>}/><Route path="/wishlist" element={<SimplePage type="Wishlist" items={books.filter(b=>wish.includes(b.id))} onCart={add}/>}/><Route path="/cart" element={<SimplePage type="Cart" items={books.filter(b=>cart.includes(b.id))} onCart={add}/>}/><Route path="/activity" element={<ActivityPage />}/><Route path="/activities" element={<Navigate to="/activity" replace />}/><Route path="/exchange" element={<ExchangeDashboard />}/><Route path="/profile" element={<ProfilePage />} /><Route path="/orders" element={<OrdersPage />} /><Route path="/wallet" element={<WalletPage />} /><Route path="/notifications" element={<NotificationsPage />} /><Route path="/chat" element={<ChatPage />} /><Route path="/settings" element={<SettingsPage />} /><Route path="/community" element={<CommunityPage />} /><Route path="*" element={<Navigate to="/" replace />}/></Routes></motion.div></AnimatePresence><Footer/></div>}
